# Generated by Django 3.2.15 on 2022-09-01 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=199, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое описание страны')),
                ('capital', models.CharField(blank=True, max_length=269, null=True, verbose_name='Столица')),
                ('is_friendly', models.BooleanField(default=False, verbose_name='Дружеская ли страна')),
                ('is_dangerous', models.BooleanField(default=False, verbose_name='Есть ли риски')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=199, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое описание документа')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='TravelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_info', models.TextField(blank=True, null=True, verbose_name='Информация о визовом порядке следования')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport.country')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport.document')),
            ],
            options={
                'verbose_name': 'Порядок пересечения',
                'verbose_name_plural': 'Порядок пересечения',
            },
        ),
        migrations.CreateModel(
            name='FavoriteCountryTG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_tg', to='passport.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_tg', to='users.telegramusers')),
            ],
            options={
                'verbose_name': 'Избранное государство пользователя телеграма',
                'verbose_name_plural': 'Избранные государства пользователей телеграма',
                'default_related_name': 'favorites_tg',
            },
        ),
        migrations.CreateModel(
            name='CountryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveSmallIntegerField(default=0, verbose_name='Срок действия документа')),
                ('image', models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='Изображение')),
                ('addition_information', models.TextField(verbose_name='Дополнительная информация')),
                ('is_biometric', models.BooleanField(default=True, verbose_name='Биометрия')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport.country')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport.document')),
            ],
            options={
                'verbose_name': 'Документ государства',
                'verbose_name_plural': 'Документы государства',
            },
        ),
        migrations.AddField(
            model_name='country',
            name='documents',
            field=models.ManyToManyField(related_name='country_doc', through='passport.CountryDocument', to='passport.Document', verbose_name='Документы'),
        ),
        migrations.AddField(
            model_name='country',
            name='orders',
            field=models.ManyToManyField(related_name='countries', through='passport.TravelOrder', to='passport.Document', verbose_name='Порядок следования'),
        ),
    ]
