# Generated by Django 3.2.15 on 2022-09-02 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritecountrytg',
            options={'default_related_name': 'favorites_tg', 'ordering': ['-id'], 'verbose_name': 'Избранное государство пользователя телеграма', 'verbose_name_plural': 'Избранные государства пользователей телеграма'},
        ),
    ]
