# Generated by Django 3.2.15 on 2022-09-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0002_alter_favoritecountrytg_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritecountrytg',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
