# Generated by Django 3.2.15 on 2022-09-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=199, unique=True, verbose_name='Имя пользователя')),
                ('chat_id', models.CharField(max_length=255, unique=True, verbose_name='Айди чата пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь телеграмма',
            },
        ),
    ]
