# Generated by Django 3.2.15 on 2022-09-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramusers',
            name='country_last_seen_pk',
            field=models.CharField(default=0, max_length=199, verbose_name='Номер страны, которую последнюю смотрел'),
        ),
    ]
